// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtvkRrS9FQvyoOew_kMGZ6-_hJDS4x5EM',
    appId: '1:321925206785:web:c4d51ea077965a0a0f4100',
    messagingSenderId: '321925206785',
    projectId: 'routeease-141ac',
    authDomain: 'routeease-141ac.firebaseapp.com',
    storageBucket: 'routeease-141ac.appspot.com',
    measurementId: 'G-FEQY0QDH0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCibME5bdjQKYRJQSCNuBg6PRYHtnom0PU',
    appId: '1:321925206785:android:3efe2335fc9321630f4100',
    messagingSenderId: '321925206785',
    projectId: 'routeease-141ac',
    storageBucket: 'routeease-141ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsreQto4-QZRz519KXNDwaTCHAitKnuTA',
    appId: '1:321925206785:ios:0793c4fee30dcad80f4100',
    messagingSenderId: '321925206785',
    projectId: 'routeease-141ac',
    storageBucket: 'routeease-141ac.appspot.com',
    iosBundleId: 'com.example.routeease',
  );
}
